package cz.muni.fi.pa165.soccermanager.enums;


/**
 * List of world stadiums.
 * @author 456519 Filip Lux
 * @version 11/18/2017.
 */
public enum StadiumEnum {
    Camp_Nou,
    Wembley_Stadium,
    Signal_Iduna_Park,
    Estadio_Santiago_Bernabeu,
    Luzhniki_Stadium,
    San_Siro,
    Stade_de_France,
    Ataturk_Olimpiyat_Stadium,
    Old_Trafford,
    Allianz_Arena,
    Olympiastadion,
    Millennium_Stadium,
    Stadio_Olimpico,
    NSC_Olimpiyskiy,
    Wanda_Metropolitano,
    OAKA_Stadium,
    Baku_Olympic_Stadium,
    Stade_Velodrome,
    Estadio_da_Luz,
    VELTINS_Arena,
    Estadio_Benito_Villamarin,
    Celtic_Park,
    Mercedes_Benz_Arena,
    Emirates_Stadium,
    Stadio_San_Paolo,
    Estadio_La_Cartuja_de_Sevilla,
    London_Stadium,
    Parc_Olympique_Lyonnais,
    Stadio_San_Nicola,
    PGE_Narodowy,
    Volksparkstadion,
    Saint_Petersburg_Stadium,
    Arena_Nationala,
    Estadio_de_Mestalla,
    Etihad_Stadium,
    ESPRIT_arena,
    Boris_Paichadze_Dinamo_Arena,
    Anfield,
    Borussia_Park,
    Hrazdan_Stadium,
    Amsterdam_ArenA,
    Estadio_San_Mames,
    Stadion_Rajko_Mitic,
    Turk_Telekom_Arena,
    St_James_Park,
    Donbass_Arena,
    Hampden_Park,
    Commerzbank_Arena,
    Izmir_Ataturk_Stadium,
    De_Kuip,
    Ibrox_Stadium,
    Ernst_Happel_Stadion,
    Sukru_Saracoglu_Stadium,
    Estadio_do_Dragao,
    Stade_Roi_Baudouin,
    Estadio_Jose_Alvalade,
    Aviva_Stadium,
    Friends_Arena,
    Stadion_Nurnberg,
    RheinEnergieStadion,
    Stade_Pierre_Mauroy,
    Fritz_Walter_Stadion,
    Stadium_of_Light,
    HDI_Arena,
    Parc_des_Princes,
    Fisht_Olympic_Stadium,
    Otkritie_Arena,
    Kazan_Arena,
    Stamford_Bridge

    }
